FileVersion = 1
Projects = {LuaTinker = {Path = "."}, "LuaTinker.Tests" = {Path = "Tests"}, "LuaTinker.Sample" = {Path = "Sample"}, KeraLua-Beef = {Git = "https://github.com/disarray2077/KeraLua-Beef"}}
ExtraPlatforms = ["Linux32", "Linux64"]

[Workspace]
StartupProject = "LuaTinker.Sample"

[Configs.Debug.Win64]
AllocStackTraceDepth = 7

[Configs.Release_O0.Win64]
LTOType = "None"
ConfigSelections = {LuaTinker = {Config = "Release"}, "LuaTinker.Tests" = {Config = "Release"}, "LuaTinker.Sample" = {Config = "Release"}}
