FileVersion = 1

[Project]
Name = "LuaTinker"
TargetType = "BeefLib"
StartupObject = "LuaTinker.Program"

[Dependencies]
corlib = "*"
KeraLua = {Git = "https://github.com/disarray2077/KeraLua-Beef"}

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "StackHelpers"

[[ProjectFolder.Items.Items]]
Type = "AutoFolder"
Name = "Translators"

[[ProjectFolder.Items.Items.Items]]
Type = "IgnoreSource"
Name = "Enumerables.bf"
