FileVersion = 1

[Project]
Name = "LuaTinker.Playground"
StartupObject = "LuaTinker.Playground.Program"

[Dependencies]
corlib = "*"
KeraLua = "*"
LuaTinker = "*"
SDL2 = "*"
BeefGL = {Git = "https://github.com/disarray2077/BeefGL"}
StbImageBeef = {Git = "https://github.com/StbBeef/StbImageBeef?path=/src/StbImageBeef"}

[Configs.Debug.Win64]
DebugCommandArguments = "gl_render.lua"

[Configs.Debug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lSDL2_image -lSDL2_mixer"

[Configs.Release.Linux64]
OtherLinkFlags = "$(LinkFlags) -lSDL2_image -lSDL2_mixer"
